######################################################################
#
# File name : tb_mdc_fft_1024_top_simulate.do
# Created on: Thu Jul 13 17:16:07 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_mdc_fft_1024_top xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_mdc_fft_1024_top_wave.do}

view wave
view structure
view signals

do {tb_mdc_fft_1024_top.udo}

run 1000ns
