######################################################################
#
# File name : tb_mdc_fft_1024_top_compile.do
# Created on: Thu Jul 13 17:16:06 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -work xil_defaultlib  \
"../../../../SDF_FFT_1024.srcs/sources_1/new/butterfly.v" \
"../../../../SDF_FFT_1024.srcs/sources_1/new/complex_mul.v" \
"../../../../SDF_FFT_1024.srcs/sources_1/new/mdc_unit.v" \
"../../../../SDF_FFT_1024.srcs/sources_1/new/twiddle_rom_1024.v" \
"../../../../SDF_FFT_1024.srcs/sources_1/new/mdc_fft_1024_top.v" \
"../../../../SDF_FFT_1024.srcs/sources_1/new/After_Convert.v" \
"../../../../SDF_FFT_1024.srcs/sources_1/new/delay_buffer.v" \
"../../../../SDF_FFT_1024.srcs/sources_1/new/Before_Convert.v" \
"../../../../SDF_FFT_1024.srcs/sources_1/new/Data_Convert.v" \
"../../../../SDF_FFT_1024.srcs/sim_1/new/tb_mdc_fft_1024_top.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

