######################################################################
#
# File name : tb_mdc_fft_1024_top_wave.do
# Created on: Wed Jun 28 16:37:20 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
