######################################################################
#
# File name : tb_sdf_fft_1024_top_wave.do
# Created on: Wed Apr 19 14:45:55 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
