######################################################################
#
# File name : tb_sdf_fft_1024_top_compile.do
# Created on: Wed Jun 28 16:27:53 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\Modelsim\\install\\win64\\vlib modelsim_lib/work
E:\\Modelsim\\install\\win64\\vlib modelsim_lib/msim

E:\\Modelsim\\install\\win64\\vlib modelsim_lib/msim/xil_defaultlib

E:\\Modelsim\\install\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

E:\\Modelsim\\install\\win64\\vlog  -incr -work xil_defaultlib  \
"../../../../SDF_FFT_1024.srcs/sources_1/new/butterfly.v" \
"../../../../SDF_FFT_1024.srcs/sources_1/new/complex_mul.v" \
"../../../../SDF_FFT_1024.srcs/sources_1/new/mdc_unit.v" \
"../../../../SDF_FFT_1024.srcs/sources_1/new/twiddle_rom_1024.v" \
"../../../../SDF_FFT_1024.srcs/sources_1/new/mdc_fft_1024_top.v" \
"../../../../SDF_FFT_1024.srcs/sources_1/new/After_Convert.v" \
"../../../../SDF_FFT_1024.srcs/sources_1/new/delay_buffer.v" \
"../../../../SDF_FFT_1024.srcs/sources_1/new/Before_Convert.v" \
"../../../../SDF_FFT_1024.srcs/sources_1/new/Data_Convert.v" \
"../../../../SDF_FFT_1024.srcs/sim_1/new/tb_mdc_fft_1024_top.v" \


# compile glbl module
E:\\Modelsim\\install\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

