# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a200tfbg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/study_file/SEU/GoodwayHouse/SDF_FFT/output/SDF_FFT_1024/SDF_FFT_1024.cache/wt [current_project]
set_property parent.project_path D:/study_file/SEU/GoodwayHouse/SDF_FFT/output/SDF_FFT_1024/SDF_FFT_1024.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/study_file/SEU/GoodwayHouse/SDF_FFT/output/IP_SDF_FFT_1024 [current_project]
update_ip_catalog
set_property ip_output_repo d:/study_file/SEU/GoodwayHouse/SDF_FFT/output/SDF_FFT_1024/SDF_FFT_1024.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/study_file/SEU/GoodwayHouse/SDF_FFT/output/SDF_FFT_1024/SDF_FFT_1024.srcs/sources_1/new/butterfly.v
  D:/study_file/SEU/GoodwayHouse/SDF_FFT/output/SDF_FFT_1024/SDF_FFT_1024.srcs/sources_1/new/complex_mul.v
  D:/study_file/SEU/GoodwayHouse/SDF_FFT/output/SDF_FFT_1024/SDF_FFT_1024.srcs/sources_1/new/delay_buffer.v
  D:/study_file/SEU/GoodwayHouse/SDF_FFT/output/SDF_FFT_1024/SDF_FFT_1024.srcs/sources_1/new/sdf_unit.v
  D:/study_file/SEU/GoodwayHouse/SDF_FFT/output/SDF_FFT_1024/SDF_FFT_1024.srcs/sources_1/new/twiddle_rom_1024.v
  D:/study_file/SEU/GoodwayHouse/SDF_FFT/output/SDF_FFT_1024/SDF_FFT_1024.srcs/sources_1/new/sdf_fft_1024_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top sdf_fft_1024_top -part xc7a200tfbg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef sdf_fft_1024_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file sdf_fft_1024_top_utilization_synth.rpt -pb sdf_fft_1024_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
